### oh-my-zsh config ###
export ZSH=$HOME/.oh-my-zsh

# theme powerlevel 10k
source /usr/local/opt/powerlevel10k/powerlevel10k.zsh-theme
[[ ! -f ~/.dotfiles/zsh/p10k.zsh ]] || source ~/.dotfiles/zsh/p10k.zsh

# history timestamps
HIST_STAMPS="yyyy-mm-dd"

# oh-my-zsh plugins
plugins=(git vagrant yarn python pip colored-man-pages docker rust cargo)

source $ZSH/oh-my-zsh.sh

source ~/.dotfiles/zsh/variables.zsh

# $PATH
source ~/.dotfiles/zsh/path.zsh

# android
source ~/.dotfiles/zsh/android.zsh

# neovim
source ~/.dotfiles/zsh/neovim.zsh

# xdebug/vscode
export XDEBUG_CONFIG="idekey=VSCODE"

### EDITOR (vim) ###
export VISUAL="vim"

# Preferred editor for local and remote sessions
if [[ -n $SSH_CONNECTION ]]; then
  export EDITOR='vim'
else
  export EDITOR='mvim'
fi

### THE FUCK (install from aur) ###
eval $(thefuck --alias)

### ALIASES ###
source ~/.dotfiles/zsh/alias.zsh

### LOCAL Environment ###
if [ -f ~/.dotfiles/zsh/local.zsh ]; then
	source ~/.dotfiles/zsh/local.zsh
fi

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
