### oh-my-zsh config ###
export ZSH=/home/$USER/.oh-my-zsh

# zsh powerlevel9k theme
ZSH_THEME="powerlevel9k/powerlevel9k"
POWERLEVEL9K_MODE="nerdfont-complete"
POWERLEVEL9K_DISABLE_RPROMPT=true
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(virtualenv dir vcs)

# Uncomment the following line to display red dots whilst waiting for completion.
COMPLETION_WAITING_DOTS="true"

# history timestamps
HIST_STAMPS="yyyy-mm-dd"

# oh-my-zsh plugins
plugins=(git vagrant yarn python pip colored-man-pages docker rust cargo)

source $ZSH/oh-my-zsh.sh

source ~/.dotfiles/zsh/variables.zsh

# $PATH
source ~/.dotfiles/zsh/path.zsh

# android
source ~/.dotfiles/zsh/android.zsh

# dotnet autocompletion
source ~/.dotfiles/zsh/dotnet.zsh

# xdebug/vscode
export XDEBUG_CONFIG="idekey=VSCODE"

### EDITOR (vim) ###
export VISUAL="vim"

# Preferred editor for local and remote sessions
if [[ -n $SSH_CONNECTION ]]; then
  export EDITOR='vim'
else
  export EDITOR='mvim'
fi

### THE FUCK (install from aur) ###
eval $(thefuck --alias)

### ALIASES ###
source ~/.dotfiles/zsh/alias.zsh

### LOCAL Environment ###
if [ -f ~/.dotfiles/zsh/local.zsh ]; then
	source ~/.dotfiles/zsh/local.zsh
fi

